version: "3.9"

services:

  # App
  app:
     build: .
     environment:
      - DATABASE_URL=postgres://root:toor@postgres:5432/DBFrutosDelPaine
      - PORT=5000
     ports:
      - "5000:5000"
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=DBFrutosDelPaine
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
  #MYSQL
  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=DBFrutosDelPaine
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_PORT=3306
    ports:
      - 3306:3306
    volumes:
      - ./mysql_data:/var/lib/mysql
      # for production ->
      #- mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - PMA_HOST=mysql
    ports:
      - 8080:80